import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";

const latoFont = localFont({
  src: [
    {
      path: '../public/fonts/Lato/Lato-Hairline.woff2',
      weight: '100',
      style: 'normal',
    },
    {
      path: '../public/fonts/Lato/Lato-Thin.woff2',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../public/fonts/Lato/Lato-Light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/Lato/Lato-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Lato/Lato-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/Lato/Lato-Semibold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/fonts/Lato/Lato-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/fonts/Lato/Lato-Heavy.woff2',
      weight: '800',
      style: 'normal',
    },
    {
      path: '../public/fonts/Lato/Lato-Black.woff2',
      weight: '900',
      style: 'normal',
    },
  ],
})
 
export const metadata: Metadata = {
  title: "Рейвуслуги",
  // description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={cn(latoFont.className, "antialiased")}
      >
        {children}
      </body>
    </html>
  );
}
